name: Doc Page Publish

on:
  push:
    branches: [main-docs]
  pull_request:
    branches: [main-docs]

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Generate Static Files
        run: npm run generate

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: .output/public
          # 直接覆盖到根目录，不再使用docs作为发布目录了
          # target-folder: docs
